openapi: 3.0.0
info:
  title: Diplom API
  version: 1.0.0
servers:
  - url: http://localhost:3001/api
    description: Локальный сервер

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [client, master]
    Service:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        price:
          type: number
        duration:
          type: integer
          description: Длительность услуги в минутах
    WorkSlot:
      type: object
      properties:
        id:
          type: integer
        master_id:
          type: integer
        date:
          type: string
          format: date
        start_time:
          type: string
        end_time:
          type: string

    AvailableTime:
      type: object
      properties:
        start:
          type: string
          description: Начало доступного интервала (HH:MM)
        end:
          type: string
          description: Конец доступного интервала (HH:MM)
      example:
        start: "10:00"
        end: "12:00"

    BookingRequest:
      type: object
      properties:
        service_id:
          type: integer
          example: 1
        work_slot_id:
          type: integer
          example: 1
        start_time:
          type: string
          example: "14:30"
        duration:
          type: integer
          example: 45

    Booking:
      type: object
      properties:
        id:
          type: integer
        client_id:
          type: integer
        service_id:
          type: integer
        work_slot_id:
          type: integer
        start_time:
          type: string
        duration:
          type: integer
        status:
          type: string
          enum: [pending, confirmed, canceled]

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        details:
          type: string

paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [client, master]
                  default: client
              example:
                username: "testuser"
                email: "test@example.com"
                password: "secret123"
                role: "client"
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      tags: [Auth]
      summary: Вход пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: "test@example.com"
                password: "secret123"
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверные учетные данные

  /auth/profile:
    get:
      tags: [Auth]
      summary: Получить профиль пользователя
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Неавторизованный доступ

  /services:
    get:
      tags: [Services]
      summary: Получить список услуг
      responses:
        '200':
          description: Список услуг
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
    post:
      tags: [Services]
      summary: Создать новую услугу (только для мастера)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Мужская стрижка"
                description:
                  type: string
                  example: "Стрижка машинкой"
                price:
                  type: number
                  example: 1500
                duration:
                  type: integer
                  example: 60
      responses:
        '201':
          description: Услуга успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '400':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизованный доступ
        '403':
          description: Недостаточно прав
    delete:
      tags: [Services]
      summary: Удалить услуги (только для мастера)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              example: [1, 2, 3]
      responses:
        '204':
          description: Услуги успешно удалены
        '403':
          description: Нет прав доступа
        '500':
          description: Ошибка сервера

  /schedule/work-slots:
    post:
      tags: [Schedule]
      summary: Создать рабочий слот (только для мастера)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                  example: "2023-10-10"
                start_time:
                  type: string
                  example: "10:00"
                end_time:
                  type: string
                  example: "21:00"
      responses:
        '201':
          description: Создан рабочий слот
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkSlot'
        '400':
          description: Неверные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизованный доступ
        '403':
          description: Недостаточно прав

  /schedule/work-slots:
    get:
      tags: [Schedule]
      summary: Получить рабочие слоты мастера (публичный доступ)
      description: Возвращает список рабочих слотов мастера для бронирования
      responses:
        '200':
          description: Список рабочих слотов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkSlot'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /schedule/available-times/{work_slot_id}::
    get:
      tags: [Schedule]
      summary: Получить доступное время для бронирования
      description: Возвращает список доступных временных интервалов в рабочем слоте
      parameters:
        - name: work_slot_id
          in: path
          required: true
          schema:
            type: integer
          example: 1
        - name: duration
          in: query
          required: true
          schema:
            type: integer
          description: Длительность услуги в минутах
          example: 30
      responses:
        '200':
          description: Список доступных временных интервалов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableTime'
        '404':
          description: Рабочий слот не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /schedule/work-slots/{id}:
    delete:
      tags: [Schedule]
      summary: Удалить рабочий слот (только для мастера)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Рабочий слот успешно удален
        '400':
          description: Нельзя удалить слот с бронированиями
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизованный доступ
        '403':
          description: Недостаточно прав
        '404':
          description: Рабочий слот не найден
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      
  /bookings:
    post:
      tags: [Bookings]
      summary: Создать бронирование (клиент)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '201':
          description: Бронирование создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '400':
          description: Неверные данные или время недоступно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неавторизованный доступ
        '403':
          description: Недостаточно прав
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'